# file: src/handlers/locations/locations.serverless.yml

list:
  handler: src/handlers/locations/list.handler
  events:
    - http: get /locations

get:
  handler: src/handlers/locations/get.handler
  events:
    - http: get /locations/{location_name}

add:
  handler: src/handlers/locations/add.handler
  events:
    - http: post /locations/add